export let textList = [
    "Explore AI without risking a robot uprising at UNSW AI society.",
    "Workshops with industry pros: learn more than just textbook theories.",
    "Tackle real-world problems, unless you prefer virtual ones.",
    "Demystify AI algorithms - it's not magic, it's just maths.",
    "Chill out at our social events — less artificial, more intelligence.",
    "Build projects that make your CV look as smart as you.",
    "Stay on the cutting edge of AI, minus the sci-fi drama.",
    "Ethics in AI: because even smart systems should play nice.",
    "Join us to find out if AI can pass your exams better than you.",
    "Ever wondered if AI could fix your love life? We haven’t figured it out either.",
    "Debate nights: where we argue whether AI or humans are better at making mistakes.",
    "Our AI projects are like our dreams: ambitious, exciting, and occasionally nonsensical.",
    "Coffee chats about whether AI will steal our jobs or just help us find better ones.",
    "We’re planning to build an AI that understands group project contributions.",
    "Spoiler: The real AI was the friends we made along the way.",
    "AI movie nights. Spoiler alert: the robots might not win this time.",
    "Discover AI applications that go beyond turning your home into a smart house.",
    "We try to make our code bug-free. Emphasis on 'try'.",
    "Like AI, we’re learning. Unlike AI, we need coffee breaks.",
    "Field trips to tech companies: see where you’ll work or whom you'll automate.",
    "Our society is like a neural network: complex, interconnected, and occasionally confusing.",
    "Our AI doesn’t predict the future, but we’re working on next week’s weather.",
    "Think you can't draw? Our AI art competitions beg to differ.",
    "Internship workshops: because even AI experts started somewhere.",
    "Seminars on AI bias: teaching algorithms not to judge a book by its cover.",
    "We don’t have flying cars, but we’re making strides in making smart ones.",
    "We debate whether AI could have written Shakespeare. So far, it’s just plagiarised him.",
    "Retro gaming nights: because sometimes the best AI is a simple one.",
    "DIY robotics workshops: come build your own (friendly) terminator.",
    "Algorithm coding challenges: may the best human (or AI) win.",
    "Career fairs: find out if your future boss is human or an algorithm.",
    "Ethical hacking workshops: breaking things to make them safer.",
    "Python coding sessions: no snakes involved, just code.",
    "Machine learning bootcamps: because your brain isn’t the only thing that can learn.",
    "AI in healthcare seminars: making medicine smarter, not harder.",
    "Quantum computing talks: where we discuss AI’s next big leap.",
    "Blockchain and AI: a match made in data heaven.",
    "Virtual reality projects: where your AI can walk before it runs.",
    "Smart city initiatives: making urban living smarter, one algorithm at a time.",
    "AI in finance seminars: because who wouldn’t want a smart wallet?",
    "Robotics competitions: may the best bot win.",
    "Augmented reality apps: blending AI with the real world.",
    "Sustainability projects: where AI helps us help the planet.",
    "Language processing workshops: teaching AI to understand our many words.",
    "Our virtual assistant can't make tea yet, but we're working on it.",
    "Do you speak Python, Java, or C++? We're multilingual!",
    "Gaming AI: where we teach computers to play fair.",
    "Data visualisation sessions: because pretty data is the best data.",

    "We're no strangers to love. You know the rules and so do I.",
    "These are not generated in real time. We're not rich. API costs are expensive.",
    "According to all known laws of aviation, there is no way a bee should be able to fly.",
    "Our president Andrew, once saved 51 children from a burning building.",
];
